language: node_js
node_js:
  - "stable"

addons:
  code_climate:
    repo_token: dc25e8d5b144cc25c390b9ec28e358aa4691e711ec179440882a3a834e52867b

script:
  - npm run test


cache:
  npm: true
  directories:
    - node_modules

before_script:
  - npm install codeclimate-test-reporter -g

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - npm run build

after_success:
  - npm run test:coverage